name: CI test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3
      - name: TZ=Asia/Taipei date
        run: TZ=Asia/Taipei date
      - name: Create JSON file
        run: echo "[\"`TZ=Asia/Taipei date -Isecond`\"]" > docs/now.json
      - name: echo "[\"`TZ=Asia/Taipei date -Isecond`\"]" > docs/now.json
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ secrets.MY_SECRET_EMAIL}}"
          git add .
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
